#ifndef TWOBLUECUBES_CATCH_WITH_MAIN_HPP_INCLUDED
#define TWOBLUECUBES_CATCH_WITH_MAIN_HPP_INCLUDED

#define CATCH_CONFIG_MAIN
#include "catch.hpp"

#endif // TWOBLUECUBES_CATCH_WITH_MAIN_HPP_INCLUDED
